#!/usr/bin/zsh

testopts() {
  # $opt will hold the current option
  local opt
  # `getopts` is a builtin for processing single-letter options
  # the while loop has `getopts ab: opt` as argument, which means that `getopt`s gets looped
  # over all the arguments until none are left.
  # "ab:" means that `a` takes no argument while `b` takes one (signified by `:`)
  # if a option is found, it is bound to `$opt`
  while getopts ab: opt; do
    # loop continues till options finished
    # see which pattern $opt matches...
    case $opt in # $opt is pattern matched against every `pattern` line until one matches
                 # and commands are executed until next `;;`
      (a) # pattern match for boolean flag `-a`
        print Option a set
        ;;
      (b) # pattern match for named argument `-b foo`
        print Option b set to $OPTARG
        ;;
      # matches a question mark
      # (and nothing else, see text)
      # `?` is how getopts signals an unknown option
      (\?)
        print Bad option, aborting.
        return 1
        ;;
    esac
  done
  # $OPTIND is set to 1 at start of every function and advanced by `getopts`
  (( OPTIND > 1 )) && shift $(( OPTIND - 1 )) # `shift` shifts off the consumed arguments
  print Remaining arguments are: $*
}

echo $(testopts -b foo -a -- args) # `--` is standard way to tell `getopts` that options are finished
