#!/usr/bin/zsh

# `typeset` creates variables with "local scope"
var='Original value'
subfn() {
  print $var
}
fn() {
  print $var
  # without `typeset`, this assignment would cause `var` to be overridden
  typeset var='Value in function'
  print $var
  subfn
}
fn
print $var


